### ISSUE TITLE
Melody compiler should have a warn method for warnings

### ISSUE THREAD

**Issue by ayusharma** [trivago/melody#12]
As of my knowledge, currently melody parser does not have a warning method. It's good to implement a `warn` method just like `error` method in `melody-parser`.

https://github.com/trivago/melody/blob/27745d7531aed047f1491c33b9306adb7df87993/packages/melody-parser/src/TokenStream.js#L109

**Comment by pago** [comment]
Might be better as part of the compiler, similar to this: https://github.com/trivago/melody/blob/27745d7531aed047f1491c33b9306adb7df87993/packages/melody-compiler/src/state/State.js#L65

The parser usually doesn't have sufficient knowledge to differentiate between a warning and an error (the AST is still in the progress of being build so we won't know much about it).

Biggest problem (and the reason why we omitted it initially): How do we report warnings? For the Webpack integration, we'd like to integrate with the loaders `warning` mechanism, for rollup we might need something different.
So we'd need a way to inject a custom logging mechanism that can be configured by the loader implementation with a fallback to `console.warn` in case none was specified.

Either way, this is a very good idea.

**Comment by ayusharma** [comment]
> So we'd need a way to inject a custom logging mechanism that can be configured by the loader implementation with a fallback to console.warn in case none was specified.

We can implement a Logger which can be bind by webpack's logging methods (this.emitWarning / this.emitError) and can have console's logging as fallback. My initial thoughts on implementation are as follows:

1. A Logger class with options (config of rollup/webpack's logging).
2. Intialization of Logger class in melody-loader with webpack/rollup logging.
3. Passing Logger's class reference to compiler. 

> Why do I need a warn method in [TokenStream](https://github.com/trivago/melody/blob/27745d7531aed047f1491c33b9306adb7df87993/packages/melody-parser/src/TokenStream.js#L109) ?

I need it to show a warn message to solve #8 . Because here we are https://github.com/trivago/melody/blob/27745d7531aed047f1491c33b9306adb7df87993/packages/melody-compiler/src/index.js#L101 adding token stream of `MountStatements` and parsing it. (it also provides a reference to [mount's parser ](https://github.com/trivago/melody/blob/27745d7531aed047f1491c33b9306adb7df87993/packages/melody-extension-core/src/parser/mount.js#L45) ).
Also [parseString](https://github.com/trivago/melody/blob/27745d7531aed047f1491c33b9306adb7df87993/packages/melody-compiler/src/index.js#L33) convert twig templates to idom's token format. so making a warn method in [state.js](https://github.com/trivago/melody/blob/27745d7531aed047f1491c33b9306adb7df87993/packages/melody-compiler/src/state/State.js#L65) will not show warning for 'as' key.

> Do we have any communitcation channel ( slack/gitter/irc ) ?

I have some doubts and it would be great to discuss..

Please correct me, If I'm wrong. Thanks.

**Comment by pago** [comment]
One reason to produce the warning as part of the compiler is that it is only relevant when compiling to idom but not needed when compiling to JSX.

The handling for `key` in the compiler can be found here (within `melody-plugin-idom`):
https://github.com/trivago/melody/blob/master/packages/melody-plugin-idom/src/visitors/mount.js#L61

There's some special handling for using `mount` within `for` and an `else` clause when no `key` is present. Once we have a `warn` method in the state, we can use it to `warn` in the `for` and `else` clauses.

The logger could be passed in as an option: https://github.com/trivago/melody/blob/master/packages/melody-compiler/src/index.js#L72 with a sensible default in case none was configured.
It should probably be a interface that is implemented and injected by the Webpack and rollup loaders as you suggested.
