### ISSUE TITLE
incorrect 'is' method call in melody-types

### ISSUE THREAD

**Issue by ayusharma** [trivago/melody#20]
In `melody-parser`, `is` method of `babel-types` has been called in a wrong way.

The `is` method signature is as follows which takes `type:string` and `node:object`:
```
function is(type, node, opts) {
  if (!node) return false;

  var matches = isType(node.type, type);
  if (!matches) return false;

  if (typeof opts === "undefined") {
    return true;
  } else {
    return t.shallowEqual(node, opts);
  }
}
```

Ref: [is Method](https://github.com/babel/babel/blob/a19349a22a0c7ca04b2ee0d3c26d46fd39e88e34/packages/babel-types/src/validators/is.js#L11)

but in `melody-types` 
https://github.com/trivago/melody/blob/e1557751063a949c9738728710609a7d052f4fda/packages/melody-types/src/index.js#L78
`node` and `types` have been passed in reverse order.

**Comment by ayusharma** [comment]
@efegurkan Could you please verify this issue. If it is an issue, I can work on it. 

Thanks.

**Comment by pago** [comment]
We don't revisit (or even look at) the nodes generated through the Babel API.
We can either correct that by applying the fix you suggested or decide we don't want it and use `babel-types` when needed.

I think fixing it would be a better approach.

**Comment by efegurkan** [comment]
I would be happy with the fix as well. @pago has more knowledge on this probably :)

**Comment by efegurkan** [comment]
#52 merged
