### ISSUE TITLE
Q: Twig Extensions and Twig Functions

### ISSUE THREAD

**Issue by bm-stschneider** [trivago/melody#41]
Is there a way to make extensions/functions/filters work with melody as well?

**Comment by bm-stschneider** [comment]
So all the custom twig extensions and so on have to be translated to plugin? What about stuff like https://symfony.com/doc/current/translation.html ?

**Comment by bm-stschneider** [comment]
Is there a tutorial to add custom plugins?

**Comment by bm-stschneider** [comment]
How do you work with translations btw?

**Comment by efegurkan** [comment]
We have custom plugins that expose a filter for translation strings.
