### ISSUE TITLE
getFocusedPath can break on IE11 for svg elements

### ISSUE THREAD

**Issue by flpwgr** [trivago/melody#57]
#### Explain the problem
When the getFocusPath fn is called passing the `node` argument an svgElement the contains method  is not part of it/

#### Expected Behaviour
Should return if node is on the root element or not (Boolean).

#### Actual Behaviour
It throws an error and break page.

#### Provide your Environment details
- Node version:
Node 8.11
- Operating System:
Windows 7/8 - IE11
- melody version:
1.04

**Comment by pago** [comment]
A polyfill for `contains` can be found here:
https://github.com/Financial-Times/polyfill-service/blob/master/packages/polyfill-library/polyfills/Node/prototype/contains/polyfill.js

For fixing the problem we have two main options:
a) Document that Node.prototype.contains must be polyfilled if IE11 & SVG elements should be supported
b) Replace usage of `node.contains` with an inlined `contains` function similar to the one from the polyfill if `node.contains` does not exist.

**Comment by danielcaldas** [comment]
Hello! I would like to take this issue.

Regarding the options @pago listed above:
a) I think if we do such thing melody enters the realm of plugins since it starts to have peer dependencies. IMO a framework must provide consistent cross-browser behaviour, and since the problem is within the framework codebase itself that is where we should tackle the problem.
b) Sounds the most reasonable approach here.

Let me know whether we agree in going with option b) and I'll give it a try.

**Comment by pago** [comment]
@danielcaldas Both are valid approaches. Melody should not include polyfills for standard behaviour as the application developers know best who their users are and which polyfills they'll need. Or they could use polyfill.io to be even more specific. A framework can't deliver that level of precision so sometimes just saying "we expect this and that environment, here's how you can polyfill it for your users" is the better choice.

In this case the logic is tiny and therefore not much of a hassle, in other cases the choice would be different.

**Comment by danielcaldas** [comment]
It depends on the granularity level that we are referring. In this case is such a small and specific issue that the effort to support it on the framework side is way less painful than to have it on the client side. But agree on the part where we should not polyfill standard behavior.
