### ISSUE TITLE
Using key in a child-component twig

### ISSUE THREAD

**Issue by Lusito** [trivago/melody#6]
I have a list twig:

```twig
<ul>
  {% for item in list %}
      {% mount './item' with {
        id: item.id
        text: item.text
      } %}
  {% endfor %}
</ul>
```

And an item twig:
```twig
<li key="li{{id}}">{{text}}</id>
```

This doesn't seem to work, except if I move the li tag to the list twig.
What is the preferred way to solve this?

**Comment by efegurkan** [comment]
Can you try to pass key to the sub element on mount tag

```twig
<ul>
  {% for item in list %}
      {% mount './item' as 'li{{item.id}}' with {
        id: item.id
        text: item.text
      } %}
  {% endfor %}
</ul>
```

**Comment by Lusito** [comment]
Thanks for the quick reply, but it doesn't interpret the `{{item.id}}` part. The result of this is that only one item is added (the last in the list)

**Comment by efegurkan** [comment]
As a workaround(not best practice), you can change the key with `loop.index0` as

```twig
 {% mount './item' as loop.index0 with {
```

**Not promising**, but I will try to find time to reproduce it.

**Comment by efegurkan** [comment]
I figured it out, if you use it this way it should work.
```twig
 {% mount './item' as 'li'+item.id with {
```

Sorry for misleading you at the first hand, inside a mount tag you can use the variables directly without mustaches.

Happy Hacking,

**Comment by Lusito** [comment]
Yes, that works. Thanks.
I'd recommend adding a note for this on your website tho, as this is not obvious.

**Comment by pago** [comment]
Twig (and thus Melody) has a (not so intuitive) different syntax for interpolation within strings. An expression like `"li#{item.id}"` should also work, see https://twig.symfony.com/doc/2.x/templates.html#string-interpolation for reference. Additionally it only works within double quoted strings.

I agree that it'd probably be worth it to document that explicitly but I'd be very interested to know what didn't work about the first example. Did you get a list with only one item (that'd be the missing string interpolation) or something entirely different (that might be a bug)?

**Comment by Lusito** [comment]
Yes, that syntax does work as well.
It was only one item on the first example.
