### ISSUE TITLE
Variable includes

### ISSUE THREAD

**Issue by PejmanPoh** [trivago/melody#77]
#### Explain the problem
Attempting to dynamically `include` `twig` files throws an error. For example, through a variable:

```
{% set abc = 'location.melody.twig' %}
<div>
    {% include "./partials/#{abc}" %}
</div> 
```

#### Expected Behaviour
The file `./partials/location.melody.twig` is loaded.

#### Actual Behaviour
Failed to compile error:

```
 ERROR in [...]/ItemDetails/index.melody.twig
    Module Error (from ./node_modules/melody-loader/lib/index.js):
    Property value expected type of string but got null
```

#### Steps to reproduce
Try to `include` a file determined through a variable.

#### Provide your Environment details
- Node version: 8.11.3

- Operating System: OSX Mojave

- melody version: 1.1.0

**Comment by pago** [comment]
It seems to be an actual bug in the Melody Compiler. I've managed to pinpoint it to this part of the code: https://github.com/trivago/melody/blob/master/packages/melody-compiler/src/convert/blocks.js#L250

where we expect the include source to be a StringLiteral. However, in your example it happens to be a BinaryExpression:

```
{ type: 'BinaryExpression',
        operator: '+',
        left:
         StringLiteral {
           loc: { source: null, start: [Object], end: [Object] },
           value: './partials/',
           [Symbol()]: [] },
        right:
         { type: 'MemberExpression',
           object: { type: 'Identifier', name: '_context$1' },
           property: { type: 'Identifier', name: 'abc' },
           computed: false } }
```

`addDefaultImportFrom` (https://github.com/trivago/melody/blob/master/packages/melody-compiler/src/state/State.js#L217) can't deal with such a type.

@PejmanPoh do you feel like you want to give it a try yourself? Or should I fix it? :)

**Comment by abertelle** [comment]
As discussed with @pago, since we are using native ES modules import syntax, the current behaviour is not an actual bug, more of a limitation.
Adding support for dynamic imports may results in new issues, so as long as there are no important use cases for it, we may better leave it aside.
Instead we decided to add a meaningful error when the include syntax is not correct.
