### ISSUE TITLE
Melody compiler should warn for mounts with no keys (no 'as')

### ISSUE THREAD

**Issue by jamesb3ll** [trivago/melody#8]
The compiler should warn if a mount has no key:
`{% mount 'component.js' %}`
Should be:
`{% mount 'component.js' as 'key' %}`

Especially in for-loops mounts should have keys.

Also update the documentation and emphasise on this.

**Comment by ayusharma** [comment]
@jamesb3ll @pago Should all mount decelerations without `as key` parameters have warning or should it only be in for-loops ?

I think, we can check this here https://github.com/trivago/melody/blob/27745d7531aed047f1491c33b9306adb7df87993/packages/melody-extension-core/src/parser/mount.js#L45

**Comment by efegurkan** [comment]
Hey, @ayusharma 

It should be for all of them AFAIK. It can be problematic in case of for loops, we are planning to enforce it.

**Comment by ayusharma** [comment]
> we are planning to enforce it.

It's better to throw an error in that condition.  

Please let me know the error format.

I am thinking of this.
```
parser.warn({
              title: "Missing 'as' key with mount.",
              pos: tokens.la(0).pos,
              advice: "There should be an 'as' argumnet with a 'key' in mount statement."
            });
```

**Comment by pago** [comment]
Has been fixed by @ayusharma and will be part of Melody 1.2.0
